### ISSUE TITLE
Suggestion to make a PlatformIO version of this repo

### ISSUE THREAD

**Issue by AlexC-0806** [teastainGit/LillyGO-T-display-S3-setup-and-examples#13]
Hello @teastainGit,

I've been exploring this repository and I find it very useful. I appreciate the effort you've put into creating and maintaining this.
I noticed that the project is currently set up for the Arduino IDE. While Arduino IDE is great, I believe that adding support for PlatformIO could make the project more accessible to a wider audience. PlatformIO offers a number of advantages such as dependency management, continuous integration support, and a more advanced IDE.
I understand that this would require some work, including reorganizing the project structure and possibly adding a `platformio.ini` configuration file. However, I believe the benefits would make it worthwhile.
Please consider this suggestion. I believe it would be a valuable addition to your project.
Thank you for your time and consideration.

Best regards,
Alex

**Comment by teastainGit** [comment]
Thanks for reaching out!
Since my repository is 'setup and examples', it does reach the wider Arduino Community. 
I feel that converting this repository to Platformio would be like playing Arduino on 'Hard'.
Could you not just copy my code and paste into a Platformio .cpp?
And add '#include arduino.h'?
I am always open to suggestions on how to make the somewhat challenging LilyGO T-Display S3 easier to setup and use.
cheers, Terry

**Comment by teastainGit** [comment]
Well, yes, I would be keen to see it!
Please let me know!
